[build-dependencies.substrate-wasm-builder]
git = 'https://github.com/paritytech/substrate'
branch = "master"
version = '4.0.0'

[package]
name = "statemint-common"
version = "0.8.30"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies.sp-consensus-aura]
default-features = false
git = 'https://github.com/paritytech/substrate'
branch = "master"
version = '0.9.0'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/paritytech/substrate'
branch = "master"
version = '3.0.0'

[dependencies.sp-io]
default-features = false
git = 'https://github.com/paritytech/substrate'
branch = "master"
version = '3.0.0'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies.frame-executive]
default-features = false
git = 'https://github.com/paritytech/substrate'
branch = "master"
version = '3.0.0'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/substrate'
branch = "master"
version = '3.0.0'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/paritytech/substrate'
branch = "master"
version = '3.0.0'


[dependencies.pallet-balances]
default-features = false
git = 'https://github.com/paritytech/substrate'
branch = "master"
version = '3.0.0'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate'
branch = "master"
version = '3.0.0'

[dependencies.sp-core]
default-features = false
git = 'https://github.com/paritytech/substrate'
branch = "master"
version = '3.0.0'

[dependencies.node-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate'
branch = "master"

[dependencies.polkadot-runtime-common]
git = 'https://github.com/paritytech/polkadot'
branch = "master"
default-features = false

# Polkadot dependencies
[dependencies.polkadot-primitives]
git = 'https://github.com/paritytech/polkadot'
branch = "master"
default-features = false

[dependencies.pallet-collator-selection]
default-features = false
path = '../../pallets/collator-selection'

[dev-dependencies]
serde = { version = "1.0.119" }

[dev-dependencies.sp-io]
default-features = false
git = 'https://github.com/paritytech/substrate'
branch = "master"
version = '3.0.0'

[dev-dependencies.pallet-authorship]
default-features = false
git = 'https://github.com/paritytech/substrate'
branch = "master"
version = '3.0.0'



[features]
default = ["std"]
std = [
	'codec/std',
	'sp-consensus-aura/std',
	'sp-std/std',
	'sp-io/std',
	'frame-support/std',
	'frame-executive/std',
	'frame-system/std',
	'pallet-collator-selection/std',
	'pallet-balances/std',
	'node-primitives/std',
	'polkadot-runtime-common/std',
	'polkadot-primitives/std',
]
