[package]
name = "assets-common"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Assets common utilities"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.9.0", default-features = false, features = ["derive"] }
log = { version = "0.4.20", default-features = false }
impl-trait-for-tuples = "0.2.2"

# Substrate
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rockmint-10005" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rockmint-10005" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rockmint-10005" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rockmint-10005" }
pallet-asset-conversion = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "rockmint-10005" }
pallet-asset-tx-payment = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "rockmint-10005" }

# Polkadot
pallet-xcm = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "rockmint-10005" }
xcm = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "rockmint-10005" }
xcm-builder = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "rockmint-10005" }
xcm-executor = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "rockmint-10005" }

# Cumulus
parachains-common = { path = "../../../common", default-features = false }
cumulus-primitives-core = { path = "../../../../primitives/core", default-features = false }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"log/std",
	"frame-support/std",
	"pallet-asset-conversion/std",
	"pallet-asset-tx-payment/std",
	"parachains-common/std",
	"cumulus-primitives-core/std",
	"sp-api/std",
	"sp-std/std",
	"sp-runtime/std",
	"pallet-xcm/std",
	"xcm/std",
	"xcm-builder/std",
	"xcm-executor/std",
]

runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
]
