[package]
name = "shell-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }

# Substrate
frame-executive = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "westmint-9425" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "westmint-9425" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "westmint-9425" }
frame-try-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true , branch = "westmint-9425" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "westmint-9425" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "westmint-9425" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "westmint-9425" }
sp-inherents = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "westmint-9425" }
sp-offchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "westmint-9425" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "westmint-9425" }
sp-session = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "westmint-9425" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "westmint-9425" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "westmint-9425" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "westmint-9425" }

# Polkadot
xcm = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "westmint-9425" }
xcm-builder = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "westmint-9425" }
xcm-executor = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "westmint-9425" }

# Cumulus
cumulus-pallet-parachain-system = { path = "../../../../pallets/parachain-system", default-features = false }
cumulus-pallet-xcm = { path = "../../../../pallets/xcm", default-features = false }
cumulus-primitives-core = { path = "../../../../primitives/core", default-features = false }
parachain-info = { path = "../../../pallets/parachain-info", default-features = false }
parachains-common = { path = "../../../common", default-features = false }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", optional = true , branch = "westmint-9425" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"scale-info/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-xcm/std",
	"cumulus-primitives-core/std",
	"parachain-info/std",
	"parachains-common/std",
	"substrate-wasm-builder",
]
try-runtime = [
	"frame-executive/try-runtime",
	"frame-try-runtime/try-runtime",
]
