[package]
name = "asset-hub-westend-integration-tests"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Asset Hub Westend runtime integration tests with xcm-emulator"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false }
assert_matches = "1.5.0"

# Substrate
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
sp-weights = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-balances = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-assets = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-asset-conversion = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }

# Polkadot
polkadot-core-primitives = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "rh-async-backing-feature" }
polkadot-parachain = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "rh-async-backing-feature" }
polkadot-runtime-parachains = { git = "https://github.com/paritytech/polkadot", branch = "rh-async-backing-feature" }
polkadot-runtime = { git = "https://github.com/paritytech/polkadot", branch = "rh-async-backing-feature" }
westend-runtime = { git = "https://github.com/paritytech/polkadot", branch = "rh-async-backing-feature" }
xcm = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "rh-async-backing-feature" }
xcm-executor = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "rh-async-backing-feature" }
pallet-xcm = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "rh-async-backing-feature" }

# Cumulus
parachains-common = { path = "../../../../common" }
penpal-runtime = { path = "../../../../runtimes/testing/penpal" }
asset-hub-westend-runtime = { path = "../../../../runtimes/assets/asset-hub-westend" }

# Local
xcm-emulator = { default-features = false, path = "../../../../../xcm/xcm-emulator" }
integration-tests-common = { default-features = false, path = "../../common" }
