[package]
name = "seedling-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.3.1", default-features = false, features = ["derive"] }

# Substrate
frame-executive = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "oty-mp-queue" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "oty-mp-queue" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "oty-mp-queue" }
pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "oty-mp-queue" }
pallet-sudo = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "oty-mp-queue" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "oty-mp-queue" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "oty-mp-queue" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "oty-mp-queue" }
sp-inherents = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "oty-mp-queue" }
sp-offchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "oty-mp-queue" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "oty-mp-queue" }
sp-session = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "oty-mp-queue" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "oty-mp-queue" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "oty-mp-queue" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "oty-mp-queue" }

# Cumulus
cumulus-pallet-parachain-system = { path = "../../../../pallets/parachain-system", default-features = false }
cumulus-pallet-solo-to-para = { path = "../../../../pallets/solo-to-para", default-features = false }
parachain-info = { path = "../../../pallets/parachain-info", default-features = false }
parachains-common = { path = "../../../common", default-features = false }
cumulus-primitives-core = { path = "../../../../primitives/core", default-features = false }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", branch = "oty-mp-queue" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"scale-info/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-sudo/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-solo-to-para/std",
	"cumulus-primitives-core/std",
	"parachain-info/std",
	"parachains-common/std",
]
