[package]
name = "cumulus-pallet-contracts-rpc"
version = "0.8.0-rc3"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/cheme/substrate/"
description = "Node-specific RPC methods for interaction with contracts."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1" }
jsonrpc-core = "14.2.0"
jsonrpc-core-client = "14.2.0"
jsonrpc-derive = "14.2.1"
sp-blockchain = { git = "https://github.com/cheme/substrate", default-features = false, branch = "rococo-branch-witness_backend" }
sp-core = { git = "https://github.com/cheme/substrate", default-features = false, branch = "rococo-branch-witness_backend" }
sp-rpc = { git = "https://github.com/cheme/substrate", default-features = false, branch = "rococo-branch-witness_backend" }
serde = { version = "1.0.101", features = ["derive"] }
sp-runtime = { git = "https://github.com/cheme/substrate", default-features = false, branch = "rococo-branch-witness_backend" }
sp-api = { git = "https://github.com/cheme/substrate", default-features = false, branch = "rococo-branch-witness_backend" }
cumulus-pallet-contracts-primitives = { path = "../common" }
cumulus-pallet-contracts-rpc-runtime-api = { path = "./runtime-api" }

[dev-dependencies]
serde_json = "1.0.41"
