name: Build

on:
  push:
    branches: [ master, integritee-v0.9.4 ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-03-25
          override: true
          target: wasm32-unknown-unknown
      - name: Install llvm-10
        run: sudo apt-get install llvm-10 clang-10
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Build
        run: cargo build --verbose --release
      - name: Upload integritee-collator
        uses: actions/upload-artifact@v2
        with:
          name: integritee-collator-${{ github.sha }}
          path: target/release/integritee-collator

  create-artifacts:
    needs: build
    runs-on: ubuntu-20.04
    env:
      CHAIN_SPEC: ${{ matrix.chain }}-${{ matrix.config }}
    strategy:
      fail-fast: false
      matrix:
        chain: [shell]
        config: [kusama]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: integritee-collator-${{ github.sha }}

      - name: 'Create binaries for artifacts'
        # Note: there is no way to pass the parachain-id to the `build-spec` cmd, which which imposes to set
        # `DEFAULT_PARA_ID=2015` in the `polkadot-parachains/command`.
        run: |
          chmod +x ./integritee-collator
          ./integritee-collator export-genesis-state --chain ${{ env.CHAIN_SPEC }} --parachain-id 2015 >  ${{ env.CHAIN_SPEC }}.state
          ./integritee-collator build-spec --chain ${{ env.CHAIN_SPEC }} --disable-default-bootnode --raw > ${{ env.CHAIN_SPEC }}.json


      - name: Compute file metadata
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          sha256sum ${{ env.CHAIN_SPEC }}.state) >> checksums.txt
          sha256sum ${{ env.CHAIN_SPEC }}.json >> checksums.txt

      - name: Upload ${{ env.CHAIN_SPEC }} Files
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.CHAIN_SPEC }}-"${{ steps.vars.outputs.sha_short }}"
          path: |
            checksums.txt
            ${{ env.CHAIN_SPEC }}.state
            ${{ env.CHAIN_SPEC }}.json
